spring:
    application:
        name: telegram-bot

    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost/telegram-devices-bot?useUnicode=true&characterEncoding=utf-8
      username: 
      password: 

    jpa:
      show-sql: true
      hibernate:
        ddlAuto: update
      properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
        hibernate.hbm2ddl.auto: validate
        hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9000

telegram:
  token: 
  username: 
  path: 

