spring:
  application:
    name: telegram-bot

  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: update

server:
  port: ${PORT:9090}
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
    min-response-size: 1024


telegram:
  token: ${TELEGRAM_TOKEN}
  username: ${TELEGRAM_USERNAME}
  path: ${TELEGRAM_URL}

