spring:
    application:
        name: telegram-bot

    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${JDBC_URL}
      username: ${JDBC_USERNAME}
      password: ${JDBC_PASSWORD}

    jpa:
      show-sql: false
      properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        hibernate.hbm2ddl.auto: update
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        hibernate.connection.pool_size: 5

server:
  port: ${PORT}

telegram:
  token: ${TELEGRAM_TOKEN}
  username: ${TELEGRAM_USERNAME}
  path: ${TELEGRAM_URL}

