spring:
  application:
    name: telegram-bot

server:
  port: ${PORT:5000}

TELEGRAM:
  TOKEN: "5651247244:AAFzRZFPYDbN9I7Oou3pGZ35gBRFCpFPsRU"
  USERNAME: "jie_mabot"
  URL: "https://bd0e-171-83-55-199.jp.ngrok.io"

SMS-MAN:
  url: "http://api.sms-man.com/stubs/handler_api.php?"
  token: "api_key=kjrwfCy-IaV76YJ6-Z2vvuNsQM0DnHk9&"
