spring:
  application:
    name: telegram-bot

server:
  port: ${PORT:5000}

TELEGRAM:
  TOKEN: "5651247244:AAFzRZFPYDbN9I7Oou3pGZ35gBRFCpFPsRU"
  USERNAME: "jie_mabot"
  URL: "https://3f58-202-43-234-99.ap.ngrok.io"

SMS-MAN:
  url: "http://api.sms-man.com/stubs/handler_api.php?"
  token: "api_key=kjrwfCy-IaV76YJ6-Z2vvuNsQM0DnHk9&"
